# Generated by Django 5.0.4 on 2025-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Unknown', max_length=255)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('contact_number', models.CharField(default='N/A', max_length=20)),
                ('course', models.CharField(default='Undeclared', max_length=100)),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned')], default='Borrowed', max_length=20)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
